In [7]:
import sklearn.datasets as ds
iris = ds.load_iris()

In [19]:
iris.data
col0 = iris.data[:,0]
col1 = iris.data[:,1]
col2 = iris.data[:,2]
col3 = iris.data[:,3]
target = iris.target

In [24]:
iris_dict={
    'Sepal Length': col0,
    'Sepal Width': col1,
    'Petal Length': col2,
    'Petal Width': col3,
    'Target': target


}

In [25]:
import pandas as pd

In [26]:
iris_df = pd.DataFrame(data=iris_dict)

In [27]:
iris_df

     Sepal Length  Sepal Width  Petal Length  Petal Width  Target
0             5.1          3.5           1.4          0.2       0
1             4.9          3.0           1.4          0.2       0
2             4.7          3.2           1.3          0.2       0
3             4.6          3.1           1.5          0.2       0
4             5.0          3.6           1.4          0.2       0
..            ...          ...           ...          ...     ...
145           6.7          3.0           5.2          2.3       2
146           6.3          2.5           5.0          1.9       2
147           6.5          3.0           5.2          2.0       2
148           6.2          3.4           5.4          2.3       2
149           5.9          3.0           5.1          1.8       2

[150 rows x 5 columns]

In [28]:
target = iris.target_names

In [29]:
target

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [34]:
iris_df.loc[iris_df['Target']==0 , 'Target'] = target[0]
iris_df.loc[iris_df['Target']==1 , 'Target'] = target[1]
iris_df.loc[iris_df['Target']==2 , 'Target'] = target[2]

In [36]:
iris_df

     Sepal Length  Sepal Width  Petal Length  Petal Width     Target
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [37]:
iris_df.to_csv('iris_exported.csv')